# Generated by Django 4.0.10 on 2025-03-12 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
