# Generated by Django 4.0.10 on 2025-03-27 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_threedmodel_delete_shape'),
        ('users', '0003_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_profiles', to='tracker.threedmodel'),
        ),
        migrations.AddField(
            model_name='profile',
            name='available_models',
            field=models.ManyToManyField(blank=True, related_name='available_in_profiles', to='tracker.threedmodel'),
        ),
    ]
