# Generated by Django 4.0.10 on 2025-02-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_like_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
