# Generated by Django 4.0.10 on 2025-03-01 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_post_likes_alter_like_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
