# Generated by Django 4.0.10 on 2025-03-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_schedule_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='duration',
            field=models.PositiveIntegerField(default=60, help_text='Duration in minutes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='duration_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='effort_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
