# Generated by Django 4.0.10 on 2025-03-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_threedmodel_delete_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='threedmodel',
            name='camera_position_z',
            field=models.FloatField(default=1.2),
        ),
    ]
