# Generated by Django 4.0.10 on 2025-03-22 03:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_phone_number'),
        ('tracker', '0009_threedmodel_delete_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='threedmodel',
            name='profile',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
