# Generated by Django 4.0.10 on 2025-03-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_threedmodel_camera_position_z'),
    ]

    operations = [
        migrations.AddField(
            model_name='threedmodel',
            name='scale',
            field=models.FloatField(default=1),
        ),
    ]
