# Generated by Django 4.0.10 on 2025-03-22 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_phone_number'),
        ('tracker', '0010_threedmodel_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threedmodel',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
