# Generated by Django 4.0.10 on 2025-03-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_threedmodel_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='threedmodel',
            name='camera_position_z',
            field=models.FloatField(default=2.2),
        ),
    ]
