# Generated by Django 4.0.10 on 2025-03-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_alter_threedmodel_camera_position_z'),
    ]

    operations = [
        migrations.AddField(
            model_name='threedmodel',
            name='camera_position_x',
            field=models.FloatField(blank=True, default=1.2, null=True),
        ),
        migrations.AddField(
            model_name='threedmodel',
            name='camera_position_y',
            field=models.FloatField(blank=True, default=1.2, null=True),
        ),
    ]
